// <auto-generated />
using System;
using DeliveryOrders.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryOrders.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240626072101_CityNameLengthIncreased")]
    partial class CityNameLengthIncreased
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryOrders.DataAccess.Models.AddressModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("AddressLine", "CityId");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DeliveryOrders.DataAccess.Models.CityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DeliveryOrders.DataAccess.Models.OrderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("CargoPickupDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<double?>("CargoWeight")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("OrderCreationDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientAddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderAddressId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipientAddressId");

                    b.HasIndex("SenderAddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DeliveryOrders.DataAccess.Models.AddressModel", b =>
                {
                    b.HasOne("DeliveryOrders.DataAccess.Models.CityModel", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("DeliveryOrders.DataAccess.Models.OrderModel", b =>
                {
                    b.HasOne("DeliveryOrders.DataAccess.Models.AddressModel", "RecipientAddress")
                        .WithMany("RecipentOrders")
                        .HasForeignKey("RecipientAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryOrders.DataAccess.Models.AddressModel", "SenderAddress")
                        .WithMany("SenderOrders")
                        .HasForeignKey("SenderAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientAddress");

                    b.Navigation("SenderAddress");
                });

            modelBuilder.Entity("DeliveryOrders.DataAccess.Models.AddressModel", b =>
                {
                    b.Navigation("RecipentOrders");

                    b.Navigation("SenderOrders");
                });

            modelBuilder.Entity("DeliveryOrders.DataAccess.Models.CityModel", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
